#!/usr/bin/env bash
# Contract checks for plain-language review-anvil output guidance.

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
ENGINE="$ROOT/SKILL.md"
ARTIFACTS="$ROOT/references/report-artifacts.md"
IMPROVE="$ROOT/../review-anvil-improve-pr/SKILL.md"
PR_SKILL="$ROOT/../review-anvil-pr/SKILL.md"
REVIEWER="$ROOT/references/reviewer-prompt.md"
REPRODUCTION="$ROOT/references/reproduction-prompt.md"
ADVERSARIAL="$ROOT/references/adversarial-prompt.md"
STYLE="$ROOT/references/asd-ste100-inspired.md"
ACTION_LOCK="$ROOT/references/action-lock-audit.md"
READONLY="$ROOT/../review-anvil-readonly/SKILL.md"
IMPROVE_PRESET="$ROOT/../review-anvil-improve-pr/SKILL.md"
PR_HELPER="$ROOT/../review-anvil-pr/scripts/pr-helper.sh"
RUN_REVIEWER="$ROOT/scripts/run-reviewer.sh"

fail() {
    printf 'test-report-language: %s\n' "$*" >&2
    exit 1
}

require() {
    local file="$1" text="$2"
    grep -Fq -- "$text" "$file" || fail "missing $text in $file"
}

reject() {
    local file="$1" text="$2"
    if grep -Fq -- "$text" "$file"; then
        fail "retired $text remains in $file"
    fi
}

require "$ENGINE" '- Checks: off | skipped (no findings needed checking)'
require "$ENGINE" '- Things to try: W items'
require "$ENGINE" '- Second check: off | <mode>, <A> reviewers'
require "$ENGINE" '- Set aside: D items'
require "$ENGINE" '- More rounds: off | not continued because <reason>'
require "$ENGINE" '**Checks:** off | skipped (no findings needed checking)'
require "$ENGINE" '**Second check:** off | <mode>, <A> reviewers'
require "$ENGINE" 'Refresh creates a session before CSRF validation'
require "$ENGINE" '- Check the state token before rotating the session.'
require "$ARTIFACTS" 'Keep the comment as short as the finding allows.'
require "$ARTIFACTS" 'stock opener or rotate through canned alternatives.'
require "$IMPROVE" 'Changes made / Things to try'
require "$ENGINE" '- Earlier review comments: none |'
require "$ENGINE" '- Checks: off | skipped | concerns='
require "$ENGINE" '- Second check: off | <mode>; reviewers='
require "$ENGINE" '- Set aside:'
require "$ENGINE" '- Next time:'
require "$ENGINE" '## What I noticed'
require "$ENGINE" '## Changes made / Things to try'
require "$ARTIFACTS" 'Write the body in this order:'
require "$ROOT/references/reviewer-prompt.md" 'Build each finding in this order: problem, impact, requested change.'
require "$ROOT/references/reviewer-prompt.md" 'For runtime bugs, include reachability.'
require "$ENGINE" 'Otherwise, add the smallest supporting fact to what you noticed.'
require "$ARTIFACTS" 'Keep only evidence that helps the author trust or fix the finding.'
require "$ARTIFACTS" 'Each sentence explains one relationship between code concepts.'
require "$ROOT/references/reviewer-prompt.md" '- evidence: required concrete proof'
require "$ROOT/references/reviewer-prompt.md" 'Prefer the smallest clear fix and existing local patterns.'
require "$ROOT/references/reviewer-prompt.md" 'Use short everyday words. Prefer one clear sentence over a dense explanation.'
require "$ROOT/references/reviewer-prompt.md" 'If not, explain why removing it is the smallest fix.'
require "$ROOT/references/reviewer-prompt.md" 'Each sentence explains one relationship between code concepts.'
require "$ROOT/references/reviewer-prompt.md" '- suggested_fix: state every concrete requested obligation and intended result.'
require "$ARTIFACTS" 'Use short everyday words. Prefer one clear sentence over a dense explanation.'
reject "$ARTIFACTS" 'vary their grammatical construction'
require "$ARTIFACTS" 'Write the body in this order:'
require "$ARTIFACTS" '**Problem:** Name the code behavior and trigger.'
require "$ARTIFACTS" '**Impact:** State the concrete bad result.'
require "$ARTIFACTS" '**Requested change:** State the exact action or decision.'
require "$ARTIFACTS" 'The title states the failure, not only its technical category.'
require "$ARTIFACTS" 'Each sentence explains one relationship between code concepts.'
require "$ARTIFACTS" 'Before emitting the body, run this author check:'
require "$ARTIFACTS" 'The title and first sentence answer: what breaks, and when?'
require "$ARTIFACTS" 'Replace an abstract label with the code actor and a direct verb.'
require "$ARTIFACTS" 'The title names the actor that produces the concrete bad result.'
require "$ARTIFACTS" "Do not attribute an aggregate run's result to one file or record inside it."
require "$ARTIFACTS" 'Rewrite the title only when every fact-lock item in it still matches.'
require "$ARTIFACTS" 'Preserve title qualifiers and ownership, including diagnostic modals and scope words.'
require "$ARTIFACTS" 'restore the synthesized finding sentence verbatim.'
require "$ARTIFACTS" 'give one minimal example instead of making the reader simulate it.'
require "$ARTIFACTS" 'Remove a test sentence only when the source does not request it.'
require "$ARTIFACTS" 'Before rewriting, make a private fact lock'
require "$ARTIFACTS" 'technical verbs and actor-action-target relationships'
require "$ARTIFACTS" 'quantifiers, scope words, and certainty'
require "$ARTIFACTS" 'valid behavior that the requested change must preserve'
require "$ARTIFACTS" 'Compare the draft with the fact lock.'
require "$ARTIFACTS" 'Clarity does not permit a stronger, broader, or different claim.'
require "$ARTIFACTS" 'Edit structure before vocabulary.'
require "$ARTIFACTS" 'Keep an exact supporting phrase for every fact-lock item.'
require "$ARTIFACTS" 'Privately map every fact-lock item to its exact supporting phrase in the draft.'
require "$ARTIFACTS" 'Do not emit until every fact-lock item has a supporting phrase.'
require "$ARTIFACTS" 'Privately map every draft relationship and boundary back to one fact-lock item.'
require "$ARTIFACTS" 'Delete any draft claim that has no source fact.'
require "$ARTIFACTS" 'If deletion would break the meaning, restore the source sentence.'
require "$ARTIFACTS" 'You may reorder clauses and split sentences'
require "$ARTIFACTS" 'Do not replace technical verbs, quantifiers, or scope words.'
require "$ARTIFACTS" 'Preserve modals that express diagnostic certainty.'
require "$ARTIFACTS" 'Treat remediation as a requested change, not as observed code.'
require "$ARTIFACTS" 'Apply the actor-action-target check to requested-change sentences as well as titles.'
require "$ARTIFACTS" 'If a requested change shifts the target, restore the source plan sentence verbatim.'
require "$ARTIFACTS" 'For each source-backed obligation in a critical, high, or medium finding'
require "$ARTIFACTS" 'Keep suggestion grammar for low and nit guidance.'
require "$ARTIFACTS" 'If no source-backed requested change exists, stop after the consequence.'
require "$ARTIFACTS" 'Do not invent why a requested test exists.'
require "$ARTIFACTS" '- Use the shared top-level parser in the module entry point.'
require "$ARTIFACTS" 'Prefer a direct verb with a concrete target, condition, or destination.'
require "$ARTIFACTS" 'For two or more independently implementable obligations'
require "$ARTIFACTS" '**Requested actions**'
require "$ARTIFACTS" 'Files containing only intentionally skipped derived rows can remain explicit exclusions; no change is requested for them.'
require "$ROOT/references/reviewer-prompt.md" 'Group requested work by implementation obligation, not by grammar.'
require "$STYLE" 'Prefer a direct verb with a concrete target, condition, or destination.'
require "$ARTIFACTS" 'Group requested work by implementation obligation, not by grammar.'
require "$ARTIFACTS" 'Do not split a list of values governed by one rule into repeated actions.'
require "$ARTIFACTS" 'Reuse exact source wording for scope and collection phrases'
require "$ROOT/references/reviewer-prompt.md" 'Do not split values governed by one rule into'
require "$ENGINE" 'Group work by cohesive implementation obligation, not by grammar'
require "$ARTIFACTS" 'An obligation is one cohesive change that can be implemented and verified'
require "$ARTIFACTS" 'Classify each source predicate before rendering it:'
require "$ARTIFACTS" 'Identify whether it describes accepted current behavior, target behavior'
require "$ARTIFACTS" 'allowed implementation boundary, or an explicitly optional follow-up.'
require "$ARTIFACTS" 'accepted current behavior, allowed implementation'
require "$ARTIFACTS" 'detaching a purpose, result, or safety clause that constrains that change.'
require "$ARTIFACTS" 'Create a separate obligation only when the source requires another'
require "$ARTIFACTS" 'Preserve accepted current behavior as standalone modal prose.'
require "$ARTIFACTS" 'a standalone optional follow-up as standalone modal prose'
require "$REVIEWER" 'without detaching a purpose,'
require "$REVIEWER" 'Preserve accepted current behavior as standalone'
require "$REVIEWER" 'modal prose. Preserve a standalone optional follow-up as standalone modal'
require "$STYLE" 'required purpose, result, or safety clause with the'
require "$ENGINE" 'keep each required purpose, result, or safety clause with the action it constrains.'
require "$ARTIFACTS" 'Apply the omission counterfactual only after that classification.'
require "$ARTIFACTS" 'leave the defect, safety boundary, or reviewer-required verification'
require "$ARTIFACTS" 'Split every sentence that mixes author work with a no-change boundary.'
require "$ARTIFACTS" 'Classify each predicate separately; do not preserve an unsplit fallback.'
require "$ARTIFACTS" 'Source intent outranks modal grammar.'
require "$ARTIFACTS" 'source-backed check, test, document change, or example stated to cover,'
require "$ARTIFACTS" 'the source explicitly calls it optional or additional.'
require "$ARTIFACTS" '`could`, and `would` do not make that work optional.'
require "$ARTIFACTS" 'A permission is not author work only when it describes acceptable unchanged'
require "$ARTIFACTS" 'A no-change boundary is not a separate obligation.'
require "$ARTIFACTS" 'Keep it out of'
require "$ARTIFACTS" '`**Requested actions**` and with the action it limits.'
require "$ARTIFACTS" 'A required source-backed test is author work'
require "$ARTIFACTS" 'Do not emit until every author-work predicate appears as an explicit'
require "$REVIEWER" 'Classify each source predicate before rendering it.'
require "$REVIEWER" 'Apply the omission counterfactual only after this classification.'
require "$REVIEWER" 'Source intent outranks modal grammar.'
require "$REVIEWER" 'permission is a no-change boundary only when it describes acceptable'
require "$REVIEWER" 'Split every sentence that mixes author work with a no-change boundary.'
require "$REVIEWER" 'do not keep an unsplit fallback.'
require "$ENGINE" 'Target behavior and required verification or documentation are author work.'
require "$ENGINE" 'Apply the omission counterfactual only after that classification.'
require "$ENGINE" 'Split every sentence that mixes author work with a no-change boundary; do not keep an unsplit fallback.'
require "$ENGINE" 'Treat source-backed verification or documentation stated to cover, demonstrate, clarify, or make a required boundary clear as author work unless it is explicitly optional.'
require "$STYLE" 'Preserve accepted current behavior and a'
require "$STYLE" 'Target behavior and required verification or'
require "$STYLE" 'documentation are author work.'
require "$STYLE" 'Source intent outranks modal grammar'
require "$STYLE" 'Never turn acceptable unchanged'
require "$ARTIFACTS" '- Require one or more values for `--models`.'
require "$ARTIFACTS" '- Add a no-match check.'
require "$ARTIFACTS" 'It can stop before existing-output discovery or publication.'
require "$ARTIFACTS" '- Enter invalid rows in `SourceConversionResult`.'
require "$ARTIFACTS" '- Fail by default for symlinks, roots, and populated targets.'
require "$ARTIFACTS" '- Reject every publisher base that is an immediate child of canonical `data`.'
require "$ARTIFACTS" '- Add mismatched source and `collection_override` tests for this path.'
require "$ARTIFACTS" 'even if the source says it “would cover” the path.'
require "$ARTIFACTS" 'Please preserve valid metrics while using source metric specs or an operator-supplied definition to establish their semantics.'
require "$ARTIFACTS" 'Two verbs that establish one invariant on the same record or output remain one obligation.'
require "$ARTIFACTS" 'After valid metrics are preserved, unresolved keys can be reported.'
require "$ARTIFACTS" 'Delete a source clause only when another retained clause states the same fact.'
require "$ENGINE" 'Run two independent post-render action-lock auditors from `references/action-lock-audit.md`'
require "$ENGINE" "Validate each auditor's complete per-ID output and combine valid failures from either auditor."
require "$ENGINE" 'force the review event to COMMENT.'
require "$ACTION_LOCK" '# Post-Render Action-Lock Audit'
require "$ACTION_LOCK" 'Dispatch two clean read-only verifier subagents in one parallel wave.'
require "$ACTION_LOCK" 'Use different model families when the'
require "$ACTION_LOCK" 'runtime permits it.'
require "$ENGINE" 'minimum source context needed to resolve antecedents and current-versus-target behavior'
require "$ACTION_LOCK" '"source_context"'
require "$ACTION_LOCK" 'Use `source_context` only to resolve antecedents and current-versus-target'
require "$ACTION_LOCK" 'Do not derive new work from it.'
require "$ACTION_LOCK" 'The already'
require "$ACTION_LOCK" 'correct exit condition is a no-change boundary.'
require "$ACTION_LOCK" '`accuracy` can remain the metric ID'
require "$ACTION_LOCK" 'Make preservation'
require "$ACTION_LOCK" 'explicit; do not request reporting.'
require "$ACTION_LOCK" 'permitted point into a “Stop before…” action.'
require "$ACTION_LOCK" 'Do not fold it into the stable-ID request.'
require "$ACTION_LOCK" '“Existing logical output can'
require "$ACTION_LOCK" 'streaming” preserves two allowed boundaries; do not turn either into an'
require "$ACTION_LOCK" 'Preserve every source condition on accepted current behavior exactly.'
require "$ACTION_LOCK" 'Compare source meaning with rendered obligation status.'
require "$ACTION_LOCK" 'Do not classify by modal grammar.'
require "$ACTION_LOCK" 'build an internal predicate ledger for each item.'
require "$ACTION_LOCK" 'Return `pass` only when every ledger row is mapped correctly.'
require "$ACTION_LOCK" '"status": "pass | fail"'
require "$ACTION_LOCK" '"missing_author_work"'
require "$ACTION_LOCK" '"false_actions"'
require "$ACTION_LOCK" '"fact_losses"'
require "$ACTION_LOCK" 'Return every input ID exactly once.'
require "$ACTION_LOCK" 'exactly one item for every input ID, no unknown or duplicate IDs'
require "$ACTION_LOCK" 'A row passes only when'
require "$ACTION_LOCK" 'both auditors return a valid `pass`.'
require "$ACTION_LOCK" 'Never use a one-item action'
require "$ACTION_LOCK" 'Never rewrite a comment.'
require "$ACTION_LOCK" 'The renderer repairs only comments with a valid failed verdict.'
require "$ACTION_LOCK" 'If either second-audit verdict fails or is unverifiable'
require "$ACTION_LOCK" 'without attempting a repair and force COMMENT.'
require "$ACTION_LOCK" 'force the review event to'
require "$ENGINE" 'each two-auditor action-lock wave'
require "$ENGINE" 'action-lock failure → restore exact source requested-work prose for every unverifiable row and force COMMENT'
require "$ENGINE" '- Check the state token before rotating the session.'
require "$ENGINE" '- Increment `attempts_succeeded` only after `insert_event` returns.'
require "$ENGINE" '- Reject invalid tokens without creating sessions.'
require "$ENGINE" '- Keep timed-out attempts eligible for retry.'
require "$ENGINE" 'every source-backed requested obligation.'
require "$ENGINE" 'The CLI help could use the same option name.'
require "$ENGINE" '- **[severity] area** — <plain-language behavior change>. (`RAV-RUN3-R2-P001`; covers `RAV-RUN3-R2-F001`)'
require "$ENGINE" 'We set this aside because <plain-language description of the missing proof>.'
require "$ENGINE" 'Keep `author-resolved` items in PR REVIEW HISTORY for reviewer context.'
require "$ENGINE" 'After synthesis and dedup, drop semantic matches to `author-resolved` items before building reproduction candidates.'
require "$ENGINE" '`author-resolved` history does not affect the review decision or approval.'
require "$ROOT/references/reviewer-prompt.md" 'Never raise an `author-resolved` item as a finding.'
require "$ROOT/../review-anvil-pr/SKILL.md" 'Only the PR author resolving a GitHub review thread creates `author-resolved` status.'
require "$ENGINE" '<!-- review-anvil: prior_feedback=reintroduced -->'
require "$ENGINE" '"prior_feedback": "reintroduced"'
require "$ARTIFACTS" 'helper-only `"prior_feedback": "reintroduced"`'
require "$ROOT/references/reviewer-prompt.md" 'only for a distinct new instance with new evidence.'
require "$STYLE" 'ASD-STE100-inspired, not ASD-STE100 compliant'
require "$STYLE" 'Use sentences of 20 words or fewer when practical.'
require "$STYLE" 'Do not rewrite code identifiers, quoted diagnostics, URLs, or required protocol/schema tokens.'
require "$STYLE" '## Internal Instructions'
require "$STYLE" 'Use active voice or a direct imperative.'
require "$STYLE" '## Author-Facing Reports and Comments'
require "$STYLE" 'Do not give a context-free command.'
require "$STYLE" 'group requested work by cohesive'
require "$STYLE" 'independently implementable obligations, use `**Requested actions**`'
for producer in "$ENGINE" "$ARTIFACTS" "$REVIEWER" "$REPRODUCTION" "$ADVERSARIAL" "$PR_SKILL" "$READONLY" "$IMPROVE" "$PR_HELPER" "$RUN_REVIEWER"; do
    require "$producer" 'asd-ste100-inspired'
done
for preset in "$IMPROVE" "$PR_SKILL"; do
    require "$preset" 'Use direct imperatives for internal steps.'
    require "$preset" 'Use `**Requested actions**` only for multiple actions the author must perform; keep no-change constraints in prose.'
done
require "$PR_HELPER" 'Review agents will inspect this PR against its base branch.'
require "$PR_HELPER" 'Fix commits will be applied to this branch after checks pass.'
require "$PR_HELPER" 'This comment will contain the final report or a failure summary.'
require "$RUN_REVIEWER" 'The reviewer output lacks a complete fenced findings block.'
reject "$PR_HELPER" "I'll run a multi-agent review loop on this PR's diff against its base branch"
for guide in "$ENGINE" "$ARTIFACTS" "$REVIEWER" "$REPRODUCTION" "$ADVERSARIAL"; do
    reject "$guide" 'We could '
    reject "$guide" 'One option is '
    reject "$guide" 'It may help to '
done
reject "$REPRODUCTION" 'author-facing wording'
reject "$REPRODUCTION" 'offer a gentle next step'
reject "$ADVERSARIAL" 'author-facing'
reject "$ADVERSARIAL" 'offer a gentle next step'
reject "$ENGINE" 'what happens because of it, and a friendly next step.'
reject "$REVIEWER" 'because of it. Then offer a friendly next step. Keep facts direct and short.'
reject "$REVIEWER" 'When useful, add a friendly next step.'
reject "$ARTIFACTS" 'Non-retryable write errors must reach `signup_flow`'
reject "$ENGINE" 'A state check before rotation would block that path.'
reject "$ENGINE" 'A missing-state-token test would cover this path.'
reject "$ENGINE" 'A timeout test can cover this path.'
reject "$ENGINE" 'friendly next step'
reject "$ARTIFACTS" 'Name `the fix` or `the corrected path` when a desired state could look like current behavior.'
reject "$ARTIFACTS" 'Use `the fix` by default.'
reject "$ARTIFACTS" 'Use `the corrected path` only when'
reject "$ARTIFACTS" 'The corrected path returns'
reject "$ENGINE" 'The corrected path checks'
reject "$ENGINE" 'The corrected path increments'
reject "$ARTIFACTS" 'Use the shared top-level parser in the module entry point. Add one offline entry-point test.'
reject "$ARTIFACTS" 'Please use the shared top-level parser in the module entry point, and add one offline entry-point test.'
reject "$ARTIFACTS" 'A concise finding can omit the requested-change sentence'
reject "$ENGINE" 'Please check the state token before rotating the session. Please reject invalid tokens'
reject "$ENGINE" 'Please increment `attempts_succeeded` only after `insert_event` returns. Please keep'
reject "$ARTIFACTS" 'can stay explicit exclusions'
reject "$ARTIFACTS" 'Files containing only intentionally skipped derived rows can stay explicit exclusions.'
reject "$ARTIFACTS" 'Keep files with only intentionally skipped derived rows as explicit exclusions.'
reject "$ARTIFACTS" 'Order the bullets as behavior change, distinct preservation path, then test.'
reject "$ARTIFACTS" '<Direct verb and distinct preserved path or exact test boundary.>'
reject "$ARTIFACTS" '- Keep empty optional cells allowed.'
reject "$ARTIFACTS" '- Keep expected 401 responses on their current handling path.'
reject "$ARTIFACTS" '- Keep schema-valid blank, unknown, or unsafe strings on the current warning path.'
reject "$ARTIFACTS" '- Add a no-match check before existing-output discovery or publication.'
reject "$ARTIFACTS" '- Report unresolved keys after the valid metrics are preserved.'
reject "$ARTIFACTS" 'A standalone permission remains prose:'
reject "$ARTIFACTS" 'Unresolved keys can be reported after the valid metrics are preserved.'
reject "$ARTIFACTS" 'may remain one obligation'
reject "$REVIEWER" 'Order behavior change, distinct preservation path, then test.'
reject "$ADVERSARIAL" 'friendly next step'
reject "$ROOT/references/reviewer-prompt.md" 'Revalidate `open`, `resolved`, `reported`, `deferred`, and'
reject "$ENGINE" '- Prior feedback: none |'
reject "$ENGINE" '- Reproduction: off | skipped | candidates='
reject "$ENGINE" '- Adversarial: off |'
reject "$ENGINE" '- Tuning suggestion:'
reject "$ENGINE" '## Diagnoses'
reject "$ENGINE" 'Possible suggestions'
reject "$ENGINE" 'failed reproduction:'
reject "$PR_SKILL" 'failed reproduction'

bash "$ROOT/scripts/test-identifiers.sh"

printf 'test-report-language: all language contract checks passed\n'
