#!/usr/bin/env bash
# Contract checks for plain-language review-anvil output guidance.

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
ENGINE="$ROOT/SKILL.md"
ARTIFACTS="$ROOT/references/report-artifacts.md"
IMPROVE="$ROOT/../review-anvil-improve-pr/SKILL.md"
PR_SKILL="$ROOT/../review-anvil-pr/SKILL.md"
REVIEWER="$ROOT/references/reviewer-prompt.md"
REPRODUCTION="$ROOT/references/reproduction-prompt.md"
ADVERSARIAL="$ROOT/references/adversarial-prompt.md"
STYLE="$ROOT/references/asd-ste100-inspired.md"
ACTION_LOCK="$ROOT/references/action-lock-audit.md"
CLARITY="$ROOT/references/clarity-pass-prompt.md"
CLARITY_VALIDATOR="$ROOT/scripts/validate-clarity-output.py"
READONLY="$ROOT/../review-anvil-readonly/SKILL.md"
IMPROVE_PRESET="$ROOT/../review-anvil-improve-pr/SKILL.md"
PR_HELPER="$ROOT/../review-anvil-pr/scripts/pr-helper.sh"
RUN_REVIEWER="$ROOT/scripts/run-reviewer.sh"

fail() {
    printf 'test-report-language: %s\n' "$*" >&2
    exit 1
}

require() {
    local file="$1" text="$2"
    grep -Fq -- "$text" "$file" || fail "missing $text in $file"
}

reject() {
    local file="$1" text="$2"
    if grep -Fq -- "$text" "$file"; then
        fail "retired $text remains in $file"
    fi
}
require "$ENGINE" 'description: Use when'
reject "$ENGINE" 'description: Iteratively refine'

require "$ENGINE" '- Checks: off | skipped (no findings needed checking)'
require "$ENGINE" '- Things to try: W items'
require "$ENGINE" '- Second check: off | <mode>, <A> reviewers'
require "$ENGINE" '- Set aside: D items'
require "$ENGINE" '- More rounds: off | not continued because <reason>'
require "$ENGINE" 'It has no Markdown heading.'
require "$ENGINE" 'Use one or two'
require "$ENGINE" 'natural sentences.'
require "$ENGINE" '<summary>Issues and fixes</summary>'
require "$ENGINE" '<summary>Optional suggestions</summary>'
require "$ENGINE" '<summary>Review context</summary>'
require "$ENGINE" 'external-facing human summary, not a visible transcript'
require "$ENGINE" 'full collapsed detail is'
require "$ENGINE" 'intentionally repeated in inline comments'
require "$ENGINE" 'GitHub'\''s native anchored review'
require "$ENGINE" '| Severity | Location | Issue | Suggested change |'
require "$ENGINE" 'Describe only what'
require "$ENGINE" 'Do not require a fixed subject'
require "$ENGINE" 'the affected area, finding count, or detected outcome'
require "$ENGINE" 'not vary wording mechanically'
require "$ENGINE" 'review-anvil footer, which is the absolute final nonblank line.'
require "$ARTIFACTS" 'footer exactly once as the absolute final nonblank line.'
require "$CLARITY" 'footer appears exactly once as the absolute final nonblank'
require "$PR_SKILL" 'footer is the absolute final nonblank line.'
require "$IMPROVE_PRESET" 'review-anvil footer remains last.'
require "$ARTIFACTS" 'Keep the comment as short as the finding allows.'
require "$ARTIFACTS" 'Do not use stock openers'
require "$IMPROVE" 'Changes made'
require "$ENGINE" '- Scope: <reviewed change>'
require "$ENGINE" '- Checks: <exact frozen check result>'
require "$ENGINE" '- Second check: <exact frozen adversarial result>'
require "$ENGINE" '- Run ordinal: <positive observed PR run ordinal | unavailable (local/degraded)>'
reject "$ENGINE" '## What I noticed'
reject "$ENGINE" '## Changes made / Things to try'
require "$ARTIFACTS" 'Write the visible body in this order:'
require "$ROOT/references/reviewer-prompt.md" 'Build each finding in this order: problem, impact, requested change.'
require "$ROOT/references/reviewer-prompt.md" 'For runtime bugs, include reachability.'
require "$ARTIFACTS" 'top-level report is a short human summary'
require "$ARTIFACTS" 'Keep only evidence that helps the author trust or fix the finding.'
require "$ARTIFACTS" 'Use one idea per sentence.'
require "$ROOT/references/reviewer-prompt.md" '- evidence: required concrete proof'
require "$ROOT/references/reviewer-prompt.md" 'Prefer the smallest clear fix and existing local patterns.'
require "$ROOT/references/reviewer-prompt.md" 'Use short everyday words. Prefer one clear sentence over a dense explanation.'
require "$ROOT/references/reviewer-prompt.md" 'If not, explain why removing it is the smallest fix.'
require "$ROOT/references/reviewer-prompt.md" 'Each sentence explains one relationship between code concepts.'
require "$ROOT/references/reviewer-prompt.md" '- suggested_fix: state every concrete requested obligation and intended result.'
require "$ARTIFACTS" 'Use short everyday words. Prefer one clear sentence over a dense explanation.'
reject "$ARTIFACTS" 'vary their grammatical construction'
require "$ARTIFACTS" 'Write the visible body in this order:'
require "$ARTIFACTS" 'One or two short sentences stating the failure and concrete result.'
require "$ARTIFACTS" 'One short direct-action paragraph when author work exists.'
require "$ARTIFACTS" 'Optional accepted behavior only when it constrains the request.'
require "$ARTIFACTS" 'Use one idea per sentence.'
require "$ARTIFACTS" 'Prefer the concrete result'
require "$ARTIFACTS" 'A reader does not need to simulate a path or helper chain.'
require "$ARTIFACTS" 'Before emitting the body, run this author check:'
require "$ARTIFACTS" 'The first sentence says what breaks and when.'
require "$ARTIFACTS" 'Every required action and verification boundary appears in the request.'
require "$ARTIFACTS" 'No sentence repeats a fact without adding a condition, result, or boundary.'
require "$ARTIFACTS" 'Before rewriting, make a private fact lock'
require "$ARTIFACTS" 'technical verbs and actor-action-target relationships'
require "$ARTIFACTS" 'quantifiers, scope words, and certainty'
require "$ARTIFACTS" 'valid behavior that the requested change must preserve'
require "$ARTIFACTS" 'Compare the draft with the fact lock.'
require "$ARTIFACTS" 'Clarity does not permit a stronger, broader, or different claim.'
require "$ARTIFACTS" 'Edit structure before vocabulary.'
require "$ARTIFACTS" 'Keep an exact supporting phrase for every fact-lock item.'
require "$ARTIFACTS" 'Privately map every fact-lock item to its exact supporting phrase in the draft.'
require "$ARTIFACTS" 'Do not emit until every fact-lock item has a supporting phrase.'
require "$ARTIFACTS" 'Privately map every draft relationship and boundary back to one fact-lock item.'
require "$ARTIFACTS" 'Delete any draft claim that has no source fact.'
require "$ARTIFACTS" 'If deletion would break the meaning, restore the source sentence.'
require "$ARTIFACTS" 'You may reorder clauses and split sentences'
require "$ARTIFACTS" 'Do not replace technical verbs, quantifiers, or scope words.'
require "$ARTIFACTS" 'Preserve modals that express diagnostic certainty.'
require "$ARTIFACTS" 'Treat remediation as a requested change, not as observed code.'
require "$ARTIFACTS" 'Do not force an actor or destination that the source does not establish.'
require "$ARTIFACTS" 'real question such as `Should …?`'
require "$ARTIFACTS" 'Every author-work predicate must remain an explicit request.'
require "$ARTIFACTS" 'Keep suggestion grammar for low'
require "$ARTIFACTS" 'If no source-backed request'
require "$ARTIFACTS" 'Do not invent why a test exists.'
require "$ARTIFACTS" 'Switch it to the shared parser'
require "$ARTIFACTS" 'Prefer a direct verb with a concrete target, condition, or destination.'
require "$ARTIFACTS" 'Use one short direct-action paragraph for one or two obligations.'
require "$ARTIFACTS" 'Use a short bullet list only for three or more'
require "$ARTIFACTS" 'keeping empty optional cells allowed.'
require "$ROOT/references/reviewer-prompt.md" 'Group requested work by implementation obligation, not by grammar.'
require "$STYLE" 'Prefer a direct verb with a concrete target, condition, or destination.'
require "$ARTIFACTS" 'Group requested work by implementation obligation, not by grammar.'
require "$ARTIFACTS" 'Do not split a list of values governed by one rule into repeated actions.'
require "$ARTIFACTS" 'Reuse exact source wording for scope and collection phrases'
require "$ROOT/references/reviewer-prompt.md" 'Do not split values governed by one rule into'
require "$ENGINE" 'Group work by cohesive implementation obligation, not by grammar'
require "$ARTIFACTS" 'An obligation is one cohesive change that can be implemented and verified'
require "$ARTIFACTS" 'Classify each source predicate before rendering it:'
require "$ARTIFACTS" 'Identify whether it describes accepted current behavior, target behavior'
require "$ARTIFACTS" 'allowed implementation boundary, or an explicitly optional follow-up.'
require "$ARTIFACTS" 'accepted current behavior, allowed implementation'
require "$ARTIFACTS" 'detaching a purpose, result, or safety clause that constrains that change.'
require "$ARTIFACTS" 'Create a separate obligation only when the source requires another'
require "$ARTIFACTS" 'Keep it in the request'
require "$ARTIFACTS" '`without changing …` or `while keeping … unchanged`.'
require "$ARTIFACTS" 'Keep optional follow-ups as optional prose.'
require "$REVIEWER" 'When accepted current'
require "$REVIEWER" 'using `without changing …` or `while keeping … unchanged`'
require "$STYLE" 'When accepted current behavior directly'
require "$STYLE" '`without changing …` or `while keeping … unchanged`.'
require "$ENGINE" 'Keep each required purpose, result, or safety clause with the action it'
require "$ARTIFACTS" 'Apply the omission counterfactual only after that classification.'
require "$ARTIFACTS" 'leave the defect, safety boundary, or reviewer-required verification'
require "$ARTIFACTS" 'Split every source sentence that mixes author work with a no-change boundary'
require "$ARTIFACTS" 'into predicates for classification; do not preserve an unsplit fallback.'
require "$ARTIFACTS" 'Source intent outranks modal grammar.'
require "$ARTIFACTS" 'source-backed check, test, document change, or example stated to cover,'
require "$ARTIFACTS" 'the source explicitly calls it optional or additional.'
require "$ARTIFACTS" '`could`, and `would` do not make that work optional.'
require "$ARTIFACTS" 'A permission is not author work only when it describes acceptable unchanged'
require "$ARTIFACTS" 'A no-change boundary is not a separate obligation.'
require "$ARTIFACTS" 'Keep it in the request'
require "$ARTIFACTS" 'A required source-backed test remains author work'
require "$ARTIFACTS" 'Every author-work predicate must remain an explicit request.'
require "$REVIEWER" 'Classify each source predicate before rendering it.'
require "$REVIEWER" 'Apply the omission counterfactual only after this classification.'
require "$REVIEWER" 'Source intent outranks modal grammar.'
require "$REVIEWER" 'permission is a no-change boundary only when it describes acceptable'
require "$REVIEWER" 'Split every source sentence that mixes author work with a no-change boundary'
require "$REVIEWER" 'into predicates for classification; do not keep an unsplit fallback.'
require "$ENGINE" 'Target behavior and required verification or documentation are author work.'
require "$ENGINE" 'Apply the omission counterfactual only after that classification.'
require "$ENGINE" 'Split every source sentence that mixes author work with a no-change boundary into predicates for classification; do not keep an unsplit fallback.'
require "$ENGINE" 'keep it in the same request sentence'
reject "$ENGINE" 'Preserve accepted current behavior or an explicitly optional follow-up as standalone modal prose.'
require "$ENGINE" 'Treat source-backed verification or documentation stated to cover, demonstrate, clarify, or make a required boundary clear as author work unless it is explicitly optional.'
require "$STYLE" 'Preserve other accepted'
require "$STYLE" 'Target behavior and required verification or'
require "$STYLE" 'documentation are author work.'
require "$STYLE" 'Source intent outranks modal grammar'
require "$STYLE" 'Never turn acceptable unchanged'
require "$ARTIFACTS" 'Switch it to the shared parser'
require "$ARTIFACTS" 'Validate uncertainty, counts, and positive denominators separately'
require "$ARTIFACTS" 'keeping empty optional cells allowed.'
require "$ARTIFACTS" 'Use one short direct-action paragraph for one or two obligations.'
require "$ARTIFACTS" 'Use a short bullet list only for three or more'
require "$ARTIFACTS" 'Keep only evidence that helps the author trust or fix the finding.'
require "$ARTIFACTS" 'A reader does not need to simulate a path or helper chain.'
require "$ARTIFACTS" 'Keep requested work calm, direct, and conversational.'
require "$ARTIFACTS" 'Use a suggestion only for a safe, exact replacement'
require "$ARTIFACTS" 'Two verbs that establish one invariant on the same record or output remain one obligation.'
require "$ARTIFACTS" 'Keep optional follow-ups as optional prose.'
require "$ARTIFACTS" 'Delete any draft claim that has no source fact.'
require "$ENGINE" 'independent post-render action-lock auditors from'
require "$ENGINE" "Validate each auditor's complete per-ID output and combine valid failures from"
require "$ENGINE" 'force the review event to COMMENT'
require "$ACTION_LOCK" '# Post-Render Action-Lock Audit'
require "$ACTION_LOCK" 'Dispatch two clean read-only verifier subagents in one parallel wave.'
require "$ACTION_LOCK" 'Use different model families'
require "$ACTION_LOCK" 'runtime permits it.'
require "$ENGINE" 'the minimum source context needed to resolve antecedents and'
require "$ENGINE" 'complete inline body.'
require "$ENGINE" 'action-lock exact-source fallback has been used'
require "$ENGINE" 'Low/nit report rows and disposition rows use suggestion/boundary mode.'
require "$ARTIFACTS" 'mandatory two-auditor action-lock gate'
require "$ACTION_LOCK" '"rendered_body"'
require "$ACTION_LOCK" 'Do not extract or summarize a request-only subset.'
require "$ACTION_LOCK" 'Convert each finding ID to a canonical'
require "$ACTION_LOCK" 'string before dispatch'
require "$ENGINE" 'Preserve an exact source suggestion only when'
require "$ENGINE" 'byte-identical validated and audited'
require "$ACTION_LOCK" 'Map every semantic predicate'
require "$ACTION_LOCK" 'Copy each input ID and `surface` verbatim'
require "$ACTION_LOCK" 'matching row remains usable.'
require "$ACTION_LOCK" 'byte-identical to the audited `rendered_body`'
require "$ACTION_LOCK" 'source-to-rendered and rendered-to-source'
require "$ACTION_LOCK" '"invented_predicates"'
require "$ACTION_LOCK" 'Required Markdown and hidden metadata are not semantic predicates.'
require "$ACTION_LOCK" 'it with `AUDIT:`'
require "$ACTION_LOCK" 'The byte-identity rule applies to passed rewrites.'
require "$ACTION_LOCK" 'exact-source fallback is exempt'
require "$ARTIFACTS" 'only when it satisfies every'
require "$ARTIFACTS" 'safety exclusion in the engine `SKILL.md`'
require "$ACTION_LOCK" 'The auditors need the whole rendered body.'
require "$ACTION_LOCK" 'Record unmatched author work'
require "$ACTION_LOCK" 'Keep `fact_losses` for source predicates'
require "$ACTION_LOCK" 'exact evidence and code fragments that the body may retain'
require "$ACTION_LOCK" 'Remove source-free predicates'
reject "$ACTION_LOCK" 'rendered_requested_work'
require "$ACTION_LOCK" '"source_context"'
require "$ACTION_LOCK" 'Use `source_context` only to resolve antecedents and current-versus-target'
require "$ACTION_LOCK" 'Do not derive new work from it.'
require "$ACTION_LOCK" 'The already'
require "$ACTION_LOCK" 'correct exit condition is a no-change boundary.'
require "$ACTION_LOCK" '`accuracy` can remain the metric ID'
require "$ACTION_LOCK" 'Make preservation'
require "$ACTION_LOCK" 'explicit; do not request reporting.'
require "$ACTION_LOCK" 'permitted point into a “Stop before…” action.'
require "$ACTION_LOCK" 'Do not fold it into the stable-ID request.'
require "$ACTION_LOCK" '“Existing logical output can'
require "$ACTION_LOCK" 'streaming” preserves two allowed boundaries; do not turn either into an'
require "$ACTION_LOCK" 'Preserve every source condition on accepted current behavior exactly.'
require "$ACTION_LOCK" 'Compare source meaning with rendered obligation status.'
require "$ACTION_LOCK" 'Do not classify by modal grammar.'
require "$ACTION_LOCK" 'build source-to-rendered and rendered-to-source'
require "$ACTION_LOCK" 'Return `pass` only when both ledgers'
require "$ACTION_LOCK" '"status": "pass | fail"'
require "$ACTION_LOCK" '"missing_author_work"'
require "$ACTION_LOCK" '"false_actions"'
require "$ACTION_LOCK" '"fact_losses"'
require "$ACTION_LOCK" 'Return every input `(id, surface)` pair exactly'
require "$ACTION_LOCK" 'exactly one item for every input `(id, surface)` pair'
require "$ACTION_LOCK" 'A row passes only when'
require "$ACTION_LOCK" 'valid `pass`.'
require "$ACTION_LOCK" 'for three or more independent inline obligations.'
require "$ACTION_LOCK" 'Never rewrite a comment.'
require "$ACTION_LOCK" 'The renderer repairs only surfaces with a valid failed verdict.'
require "$ACTION_LOCK" 'If either second-audit verdict fails or is unverifiable'
require "$ACTION_LOCK" 'without attempting a repair and force'
require "$ACTION_LOCK" 'force the review event to'
require "$ACTION_LOCK" '"surface": "report | inline"'
require "$ACTION_LOCK" 'Return every input `(id, surface)` pair exactly'
require "$ACTION_LOCK" 'Audit report and inline surfaces independently.'
require "$ACTION_LOCK" 'does not satisfy the ledger.'
require "$ACTION_LOCK" '"source_fact_lock"'
require "$ACTION_LOCK" 'Every `source_fact_lock` predicate must appear'
require "$ACTION_LOCK" 'Fact locks are surface-specific.'
require "$ENGINE" 'source fact locks'
require "$ENGINE" 'each two-auditor action-lock wave'
require "$ACTION_LOCK" 'Do not wrap JSON in a Markdown fence.'
require "$ACTION_LOCK" '"request_mode": "required | suggested | boundary"'
require "$ACTION_LOCK" 'critical/high/medium report-table rows use `required`'
require "$ACTION_LOCK" 'not imperative.'
require "$CLARITY" 'Low and nit report items keep suggestion grammar.'
require "$CLARITY" '"decision": "APPROVE | COMMENT"'
require "$CLARITY" 'even when an inline comment exists.'
reject "$CLARITY" 'Findings below'
reject "$PR_SKILL" 'natural bold title'
require "$ACTION_LOCK" 'using `without changing …` or `while keeping … unchanged`'
require "$ACTION_LOCK" 'does not turn that boundary into'
require "$ENGINE" 'derive `request_mode` from severity, surface, and'
require "$ENGINE" 'The handler creates a session before it checks the state token'
require "$ENGINE" 'Check the token first'
require "$ENGINE" 'The retry block counts the attempt as successful'
require "$ENGINE" 'Increment `attempts_succeeded` only after the write returns'
require "$ENGINE" 'smallest source-backed request'
require "$ENGINE" 'No machine metadata or'
require "$ENGINE" 'Low/nit report rows and disposition rows use suggestion/boundary mode.'
require "$ENGINE" 'We set this aside because <plain-language description of the missing proof>.'
require "$ENGINE" 'Keep `author-resolved` items in PR REVIEW HISTORY for reviewer context.'
require "$ENGINE" 'After synthesis and dedup, drop semantic matches to `author-resolved` items before building reproduction candidates.'
require "$ENGINE" '`author-resolved` history does not affect the review decision or approval.'
require "$ROOT/references/reviewer-prompt.md" 'Never raise an `author-resolved` item as a finding.'
require "$ROOT/../review-anvil-pr/SKILL.md" 'Only the PR author resolving a GitHub review thread creates `author-resolved` status.'
require "$ENGINE" '<!-- review-anvil: prior_feedback=reintroduced -->'
require "$ENGINE" '"prior_feedback": "reintroduced"'
require "$ARTIFACTS" '`"prior_feedback": "reintroduced"`'
require "$ROOT/references/reviewer-prompt.md" 'only for a distinct new instance with new evidence.'
require "$STYLE" 'ASD-STE100-inspired, not ASD-STE100 compliant'
require "$STYLE" 'Use sentences of 20 words or fewer when practical.'
require "$STYLE" 'Do not rewrite code identifiers, quoted diagnostics, URLs, or required protocol/schema tokens.'
require "$STYLE" '## Internal Instructions'
require "$STYLE" 'Use active voice or a direct imperative.'
require "$STYLE" '## Author-Facing Reports and Comments'
require "$STYLE" 'Do not give a context-free command.'
require "$STYLE" 'group requested work by cohesive'
require "$STYLE" 'Default to starting required work with its action verb.'
require "$STYLE" 'Keep one or two'
require "$STYLE" 'cohesive obligations in one short prose paragraph.'
require "$STYLE" 'For three or more'
require "$STYLE" 'independently implementable obligations, use one direct-action bullet per'
reject "$STYLE" 'Use `Please` plus an action verb'
reject "$STYLE" '**What to change**'
require "$REVIEWER" 'Default to starting required work with its action verb.'
require "$REVIEWER" 'Keep one or two'
require "$REVIEWER" 'cohesive obligations in one short prose paragraph.'
require "$REVIEWER" 'For three or more'
require "$REVIEWER" 'independently implementable obligations, use one direct-action Markdown'
reject "$REVIEWER" 'beginning with `Please`'
reject "$REVIEWER" '**What to change**'
require "$ENGINE" 'Run one clean final clarity pass after the report facts are frozen'
require "$ENGINE" 'the top-level report and eligible inline comments in one bundle.'
require "$ENGINE" 'validate-clarity-output.py'
require "$ENGINE" 'Do not post or approve an unvalidated clarity bundle.'
require "$ENGINE" 'report and inline bodies, force the review event to COMMENT'
require "$ARTIFACTS" 'top-level report is a short human summary'
require "$ARTIFACTS" 'full diagnosis'
require "$ARTIFACTS" 'inline comments retain the same'
require "$CLARITY" '# Final Clarity Pass'
require "$CLARITY" 'The input is a frozen fact packet'
require "$CLARITY" 'Do not add, remove, merge, split, reprioritize, or'
require "$CLARITY" 'open | still-present | fixed | stale | reported | author-resolved'
require "$CLARITY" 'Return one JSON object'
require "$CLARITY" '"report_markdown"'
require "$CLARITY" '"inline_comments"'
require "$CLARITY" '"report_ids"'
require "$CLARITY" 'complete report identity inventory'
require "$ENGINE" 'complete report ID inventory'
require "$CLARITY" '"metadata_inventory"'
require "$CLARITY" 'Copy every frozen metadata and disposition field byte-for-byte'
require "$CLARITY" '"prior_feedback": "reintroduced"'
require "$ENGINE" 'structured disposition inventory'
require "$ENGINE" 'prior_feedback'
require "$CLARITY" 'earlier-feedback line uses the existing exact tuple'
require "$CLARITY" '- **<status>** — <exact text> <exact URL> (`<finding ID>`)'
require "$CLARITY" '"predicate_inventory"'
require "$CLARITY" '## Quick reference'
require "$CLARITY" '## Common rendering mistakes and red flags'
require "$CLARITY" 'Build a semantic union of `requested_work` entries per finding.'
require "$CLARITY" 'verification boundary, and no-change boundary in the collapsed'
require "$CLARITY" 'can map to one predicate per surface'
require "$CLARITY" 'requested verification gets none.'
require "$CLARITY" 'Do not invent a test purpose, outcome, or'
require "$CLARITY" 'Keep every safe exact `suggestion`'
require "$CLARITY_VALIDATOR" 'report finding inventory mismatch'
require "$CLARITY_VALIDATOR" 'safe suggestion changed'
require "$ENGINE" 'No machine metadata or'
require "$CLARITY" 'id=<complete-id> severity=<severity> area=<area> path=<encoded-path>'
require "$CLARITY" 'Emit inline comments only at or above the'
require "$ENGINE" 'id=<complete-id> severity=<severity> area=<area> path=<encoded-path>'
require "$CLARITY_VALIDATOR" 'HUMAN_REPORT_ITEM_RE'
require "$CLARITY" '"inline_min_severity": "medium"'
require "$CLARITY" 'Emit inline comments only at or above the'
require "$ENGINE" 'resolved inline severity threshold'
require "$CLARITY" 'Inline anchors and report locations are'
require "$PR_HELPER" 'HUMAN_REPORT_RE'
require "$ENGINE" 'validated `report_markdown` string to `report_path`'
require "$CLARITY" 'A top-level summary is one or two natural sentences'
require "$CLARITY" 'Inline comments'
require "$CLARITY" 'same anchored detail in GitHub'
require "$CLARITY" 'The top-level report has no Markdown heading.'
require "$CLARITY" 'Write one or two natural visible'
require "$CLARITY" '<summary>Issues and fixes</summary>'
require "$CLARITY" '<summary>Optional suggestions</summary>'
require "$CLARITY" '<summary>Review context</summary>'
require "$CLARITY" '| Severity | Location | Issue | Suggested change |'
require "$CLARITY" '| Severity | Location | Suggestion | Suggested change |'
require "$CLARITY" 'Each table row stays on one source line'
require "$CLARITY" 'Escape every literal'
require "$CLARITY" '`|` inside a cell as `\|`'
require "$CLARITY" 'Describe only what the review detected'
require "$CLARITY" 'Do not require a fixed subject or opening phrase.'
require "$CLARITY" 'Start with the affected area, finding count, or detected outcome'
require "$CLARITY" 'Do not vary wording mechanically.'
require "$ARTIFACTS" '| Severity | Location | Issue | Suggested change |'
reject "$CLARITY" 'I would not merge'
reject "$CLARITY" '**Changes requested.**'
require "$CLARITY" 'Inline comments use two short human paragraphs'
require "$CLARITY" 'Default to starting required work with its action verb.'
require "$ARTIFACTS" 'Default to starting required work with its action verb.'
require "$ENGINE" 'Default to starting required work with its action verb.'
reject "$CLARITY" 'Could you switch it to the shared parser'
require "$CLARITY" 'End a direct imperative as a'
require "$ARTIFACTS" 'End a direct imperative as a'
require "$CLARITY" 'statement, not a question.'
require "$ARTIFACTS" 'statement, not a question.'
require "$CLARITY" 'Simplify the contents, not only the formatting.'
require "$CLARITY" 'Use one idea per sentence'
require "$CLARITY" 'Prefer the concrete outcome'
require "$CLARITY" 'A reader should not have to simulate'
require "$CLARITY" '"disposition_items"'
require "$CLARITY" '"set_aside": [{"id":'
require "$CLARITY" 'id=<complete-id> severity=<severity> area=<area> path=<encoded-path>'
reject "$CLARITY" '**What to change**'
reject "$CLARITY" 'The final parenthesis contains only the stable finding ID.'
require "$ENGINE" 'and write only validated'
require "$ENGINE" 'Never post `report_items`'
for producer in "$ENGINE" "$ARTIFACTS" "$REVIEWER" "$REPRODUCTION" "$ADVERSARIAL" "$PR_SKILL" "$READONLY" "$IMPROVE" "$PR_HELPER" "$RUN_REVIEWER"; do
    require "$producer" 'asd-ste100-inspired'
done
for preset in "$IMPROVE" "$PR_SKILL"; do
    require "$preset" 'Use direct imperatives for internal steps.'
    require "$preset" 'default to starting required work with its action verb and use bullets only for three or more independent actions.'
    require "$preset" 'collaborative request may use a courtesy wrapper'
    require "$preset" 'coordination or'
    require "$preset" 'tone benefits.'
done
for producer in "$ENGINE" "$ARTIFACTS" "$REVIEWER" "$STYLE" "$CLARITY"; do
    require "$producer" 'collaborative request may use a courtesy wrapper'
    require "$producer" 'coordination or'
    require "$producer" 'tone benefits.'
done
reject "$ARTIFACTS" 'not courtesy wrappers such as'
reject "$ENGINE" 'do not use `Could you`'
for producer in "$ENGINE" "$ARTIFACTS" "$REVIEWER" "$STYLE" "$ACTION_LOCK" "$PR_SKILL" "$IMPROVE_PRESET"; do
    reject "$producer" '**Requested actions**'
done
require "$PR_HELPER" 'Review agents will inspect this PR against its base branch.'
require "$PR_HELPER" 'Fix commits will be applied to this branch after checks pass.'
require "$PR_HELPER" 'This comment will contain the final report or a failure summary.'
require "$RUN_REVIEWER" 'The reviewer output lacks a complete fenced findings block.'
reject "$PR_HELPER" "I'll run a multi-agent review loop on this PR's diff against its base branch"
for guide in "$ENGINE" "$ARTIFACTS" "$REVIEWER" "$REPRODUCTION" "$ADVERSARIAL"; do
    reject "$guide" 'We could '
    reject "$guide" 'One option is '
    reject "$guide" 'It may help to '
done
reject "$REPRODUCTION" 'author-facing wording'
reject "$REPRODUCTION" 'offer a gentle next step'
reject "$ADVERSARIAL" 'author-facing'
reject "$ADVERSARIAL" 'offer a gentle next step'
reject "$ENGINE" 'what happens because of it, and a friendly next step.'
reject "$REVIEWER" 'because of it. Then offer a friendly next step. Keep facts direct and short.'
reject "$REVIEWER" 'When useful, add a friendly next step.'
reject "$ARTIFACTS" 'Non-retryable write errors must reach `signup_flow`'
reject "$ENGINE" 'A state check before rotation would block that path.'
reject "$ENGINE" 'A missing-state-token test would cover this path.'
reject "$ENGINE" 'A timeout test can cover this path.'
reject "$ENGINE" 'friendly next step'
reject "$ARTIFACTS" 'Name `the fix` or `the corrected path` when a desired state could look like current behavior.'
reject "$ARTIFACTS" 'Use `the fix` by default.'
reject "$ARTIFACTS" 'Use `the corrected path` only when'
reject "$ARTIFACTS" 'The corrected path returns'
reject "$ENGINE" 'The corrected path checks'
reject "$ENGINE" 'The corrected path increments'
reject "$ARTIFACTS" 'Use the shared top-level parser in the module entry point. Add one offline entry-point test.'
reject "$ARTIFACTS" 'Please use the shared top-level parser in the module entry point, and add one offline entry-point test.'
reject "$ARTIFACTS" 'A concise finding can omit the requested-change sentence'
reject "$ENGINE" 'Please check the state token before rotating the session. Please reject invalid tokens'
reject "$ENGINE" 'Please increment `attempts_succeeded` only after `insert_event` returns. Please keep'
reject "$ARTIFACTS" 'can stay explicit exclusions'
reject "$ARTIFACTS" 'Files containing only intentionally skipped derived rows can stay explicit exclusions.'
reject "$ARTIFACTS" 'Keep files with only intentionally skipped derived rows as explicit exclusions.'
reject "$ARTIFACTS" 'Order the bullets as behavior change, distinct preservation path, then test.'
reject "$ARTIFACTS" '<Direct verb and distinct preserved path or exact test boundary.>'
reject "$ARTIFACTS" '- Keep empty optional cells allowed.'
reject "$ARTIFACTS" '- Keep expected 401 responses on their current handling path.'
reject "$ARTIFACTS" '- Keep schema-valid blank, unknown, or unsafe strings on the current warning path.'
reject "$ARTIFACTS" '- Add a no-match check before existing-output discovery or publication.'
reject "$ARTIFACTS" '- Report unresolved keys after the valid metrics are preserved.'
reject "$ARTIFACTS" 'A standalone permission remains prose:'
reject "$ARTIFACTS" 'Unresolved keys can be reported after the valid metrics are preserved.'
reject "$ARTIFACTS" 'may remain one obligation'
reject "$REVIEWER" 'Order behavior change, distinct preservation path, then test.'
reject "$ADVERSARIAL" 'friendly next step'
reject "$ROOT/references/reviewer-prompt.md" 'Revalidate `open`, `resolved`, `reported`, `deferred`, and'
reject "$ENGINE" '- Prior feedback: none |'
reject "$ENGINE" '- Reproduction: off | skipped | candidates='
reject "$ENGINE" '- Adversarial: off |'
reject "$ENGINE" '- Tuning suggestion:'
reject "$ENGINE" '## Diagnoses'
reject "$ENGINE" 'Possible suggestions'
reject "$ENGINE" 'failed reproduction:'
reject "$PR_SKILL" 'failed reproduction'

bash "$ROOT/scripts/test-identifiers.sh"

printf 'test-report-language: all language contract checks passed\n'
